Merged bugfix/WC-1382-unicode-fix into develop
* WC-1391: parser tests: Add test case.

    This is an actual grid returned by our WideSky instance that made
    `hszinc` choke.  Now to fix the cause.

* WC-1391: zincparser: Improve error reporting.

    Now, if an error is detected in a ZINC grid, an exception is thrown
    which gives the location of the error in both human and machine-readable
    forms:

    ```
    ======================================================================
    ERROR: tests.test_parser.test_list_v2
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/stuartl/vrt/projects/widesky/sdk/hszinc/tests/test_parser.py", line 657, in test_list_v2
        ''')
      File "/home/stuartl/vrt/projects/widesky/sdk/hszinc/hszinc/parser.py", line 48, in parse
        return list(map(_parse, GRID_SEP.split(grid_str.rstrip())))
      File "/home/stuartl/vrt/projects/widesky/sdk/hszinc/hszinc/parser.py", line 58, in parse_grid
        return parse_zinc_grid(grid_str)
      File "/home/stuartl/vrt/projects/widesky/sdk/hszinc/hszinc/zincparser.py", line 559, in parse_grid
        g.extend(map(_parse_row, filter(lambda gp : bool(gp[1]), enumerate(grid_parts))))
      File "/home/stuartl/vrt/projects/widesky/sdk/hszinc/hszinc/zincparser.py", line 550, in _parse_row
        grid_data, line_num, pe.col)
    ZincParseException: Failed to parse row: Expected end of text (at char 3), (line:3, col:4)
        .-------------------------------------------------------------------------------------.
       1| ver:"2.0"                                                                           |
       2| ix,list,                                                       dis                  |
       3 >00,[],                                                         "An empty list"     <
        |   .^.                                                                               |
       4| 01,[N],                                                        "A list with a NULL" |
        '-------------------------------------------------------------------------------------'
    ```

    The exception error has the following properties:
    * `grid_str`: The raw grid/scalar string, as received by the parser.
    * `line`: Line number where the error occurred (above example would be
       `3`).
    * `col`: Column number where the error occurred (above example would be
      `4`).

* WC-1391: zincparser: Drop character number reference.

    Useless to us, as it's from the start of the line, it basically
    duplicates the column number.

* WC-1391: Fix WC-1382 unit test

    As it turns out, the problem was the presence of `true` and `false` in
    the ZINC output, which is Not Allowed.  It's actually a WideSky bug, and
    as such, the fix belongs there.

    This became apparent once I made the previous commits to improve the
    error reporting, it was now blindlingly obvious where the problem
    existed.

* WC-1391: parser tests: Use new exception class.

    We now throw `ZincParseException` on failed parsing.  This is a
    sub-class of `ValueError`.

* WC-1391: MANIFEST.in: Add test data.

    Some test files are needed in the sources for people to run tests.  Some
    other files are needed to shut `dpkg-buildpackage` up.

* WC-1391: parser tests: Derive file path to data file.

    Rather than relying on the test cases running from a "blessed"
    directory.

* WC-1391: zincparser: Make line and col mandatory.

    There's actually no cases where we need to make them optional, so force
    these to be specified.

* WC-1391: parser tests: Test obvious mistakes.

    Ensure that all the unhappy paths in the parser are covered.